### ISSUE TITLE
Possible PR

### ISSUE THREAD

**Issue by philipturner** [manjunath5496/3D-reconstruction-Paper-list#1]
I have a research paper on [adding color to scene reconstruction](https://github.com/philipturner/scene-color-reconstruction) that just got rejected from openMVG/awesome_3DReconstruction_list. Would mine qualify for this repository?

**Comment by manjunath5496** [comment]
Respected sir,

your paper has been added to

https://github.com/manjunath5496/3D-reconstruction-Paper-list/blob/master/README.md

Take for your contribution and keep going with your good work

Your obedient servant

Manjunath.R

**Comment by philipturner** [comment]
Thank you so much!

**Comment by philipturner** [comment]
I just released [ARHeadsetKit](https://github.com/philipturner/ARHeadsetKit), which is related to my research in scene color reconstruction. It has a [list of articles](https://github.com/philipturner/ARHeadsetKit/blob/main/docs/article-list.md), which I will add more content to in the future. It only has one article right now, but the article is really awesome.

Also, do you prefer to be contacted by email?

**Comment by manjunath5496** [comment]
Respected sir,

What Help is needed?

**Comment by philipturner** [comment]
I would like you to look at my list of articles. I'm also asking if we could continue this conversion over email because it's a bit awkward on GitHub.

**Comment by manjunath5496** [comment]
Yes, awesome list of articles
